//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubiquity.NET.CommandLine.SrcGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubiquity.NET.CommandLine.SrcGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property has incorrect type for attribute.
        /// </summary>
        internal static string IncorrectPropertyType_Description {
            get {
                return ResourceManager.GetString("IncorrectPropertyType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property attribute &apos;{0}&apos; requires a property of type &apos;{1}&apos;..
        /// </summary>
        internal static string IncorrectPropertyType_MessageFormat {
            get {
                return ResourceManager.GetString("IncorrectPropertyType_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property has incorrect type for attribute.
        /// </summary>
        internal static string IncorrectPropertyType_Title {
            get {
                return ResourceManager.GetString("IncorrectPropertyType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal analyzer exception occurred..
        /// </summary>
        internal static string InternalError_Description {
            get {
                return ResourceManager.GetString("InternalError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message is: &apos;{0}&apos;.
        /// </summary>
        internal static string InternalError_MessageFormat {
            get {
                return ResourceManager.GetString("InternalError_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        internal static string InternalError_Title {
            get {
                return ResourceManager.GetString("InternalError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property attribute only allowed on an attributed command class.
        /// </summary>
        internal static string MissingCommandAttribute_Description {
            get {
                return ResourceManager.GetString("MissingCommandAttribute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property attribute &apos;{0}&apos; is only allowed on a property in a type attributed with a command attribute. This use will be ignored by the generator..
        /// </summary>
        internal static string MissingCommandAttribute_MessageFormat {
            get {
                return ResourceManager.GetString("MissingCommandAttribute_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing command attribute on containing type.
        /// </summary>
        internal static string MissingCommandAttribute_Title {
            get {
                return ResourceManager.GetString("MissingCommandAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property attribute not allowed standalone.
        /// </summary>
        internal static string MissingConstraintAttribute_Description {
            get {
                return ResourceManager.GetString("MissingConstraintAttribute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property attribute &apos;{0}&apos; is not allowed on a property independent of a qualifying attribute such as OptionAttribute..
        /// </summary>
        internal static string MissingConstraintAttribute_MessageFormat {
            get {
                return ResourceManager.GetString("MissingConstraintAttribute_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property attribute not allowed standalone.
        /// </summary>
        internal static string MissingConstraintAttribute_Title {
            get {
                return ResourceManager.GetString("MissingConstraintAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type does not support the arity specified.
        /// </summary>
        internal static string PropertyTypeArityMismatch_Description {
            get {
                return ResourceManager.GetString("PropertyTypeArityMismatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; has type of &apos;{1}&apos; which does not support an arity of ({2}, {3})..
        /// </summary>
        internal static string PropertyTypeArityMismatch_MessageFormat {
            get {
                return ResourceManager.GetString("PropertyTypeArityMismatch_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arity specified for property type is invalid..
        /// </summary>
        internal static string PropertyTypeArityMismatch_Title {
            get {
                return ResourceManager.GetString("PropertyTypeArityMismatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type is nullable but marked as required; These annotations conflict resulting in behavior that is explicitly UNDEFINED..
        /// </summary>
        internal static string RequiredNullableType_Description {
            get {
                return ResourceManager.GetString("RequiredNullableType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; for property &apos;{1}&apos; is nullable but marked as required; These annotations conflict resulting in behavior that is explicitly UNDEFINED..
        /// </summary>
        internal static string RequiredNullableType_MessageFormat {
            get {
                return ResourceManager.GetString("RequiredNullableType_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type is nullable but marked as required..
        /// </summary>
        internal static string RequiredNullableType_Title {
            get {
                return ResourceManager.GetString("RequiredNullableType_Title", resourceCulture);
            }
        }
    }
}
