// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     testhost [18.0.1]
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using static global::Ubiquity.NET.CommandLine.SymbolValidationExtensions;

namespace TestNamespace
{
    internal partial class TestOptions
        : global::Ubiquity.NET.CommandLine.IRootCommandBuilderWithSettings
        , global::Ubiquity.NET.CommandLine.ICommandBinder<TestOptions>
    {
        public static global::Ubiquity.NET.CommandLine.CommandLineSettings Settings => new();

        public static TestOptions Bind( global::System.CommandLine.ParseResult parseResult )
        {
            return new()
            {
                SomePath = parseResult.GetValue( Descriptors.SomePath ),
                SomeExistingPath = parseResult.GetValue( Descriptors.SomeExistingPath ),
                Thing1 = parseResult.GetRequiredValue( Descriptors.Thing1 ),
                SomeOtherPath = parseResult.GetValue( Descriptors.SomeOtherPath ),
            };
        }

        public static global::Ubiquity.NET.CommandLine.AppControlledDefaultsRootCommand Build( )
        {
            return new global::Ubiquity.NET.CommandLine.AppControlledDefaultsRootCommand( Settings, "Root command for tests" )
            {
                Descriptors.SomePath,
                Descriptors.SomeExistingPath,
                Descriptors.Thing1,
                Descriptors.SomeOtherPath,
            };
        }
    }

    file static class Descriptors
    {
        internal static readonly global::System.CommandLine.Option<global::System.IO.DirectoryInfo> SomePath
            = new global::System.CommandLine.Option<global::System.IO.DirectoryInfo>("-o")
            {
                Description = "Test SomePath",
            }.EnsureFolder();

        internal static readonly global::System.CommandLine.Option<global::System.IO.DirectoryInfo> SomeExistingPath
            = new global::System.CommandLine.Option<global::System.IO.DirectoryInfo>("-b")
            {
                Description = "Test Some existing Path",
            }.AcceptExistingFolderOnly();

        internal static readonly global::System.CommandLine.Option<bool> Thing1
            = new global::System.CommandLine.Option<bool>("--thing1", "-t")
            {
                HelpName = "Help name for thing1",
                Description = "Test Thing1",
                Required = true,
            };

        internal static readonly global::System.CommandLine.Option<global::System.IO.FileInfo> SomeOtherPath
            = new global::System.CommandLine.Option<global::System.IO.FileInfo>("-a")
            {
                Description = "Test SomeOtherPath",
                Required = false,
                Hidden = true,
                Arity = new global::System.CommandLine.ArgumentArity(0, 3),
            }.AcceptExistingFileOnly();
    }
}
