// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     testhost [18.0.1]
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using static global::Ubiquity.NET.CommandLine.SymbolValidationExtensions;

namespace TestNamespace
{
    internal partial class TestOptions
        : global::Ubiquity.NET.CommandLine.IRootCommandBuilderWithSettings
        , global::Ubiquity.NET.CommandLine.ICommandBinder<TestOptions>
    {
        public static global::Ubiquity.NET.CommandLine.CommandLineSettings Settings => new();

        public static TestOptions Bind( global::System.CommandLine.ParseResult parseResult )
        {
            return new()
            {
                Thing1 = parseResult.GetValue( Descriptors.Thing1 ),
            };
        }

        public static global::Ubiquity.NET.CommandLine.AppControlledDefaultsRootCommand Build( )
        {
            return new global::Ubiquity.NET.CommandLine.AppControlledDefaultsRootCommand( Settings, "Root command for tests" )
            {
                Descriptors.Thing1,
            };
        }
    }

    file static class Descriptors
    {
        internal static readonly global::System.CommandLine.Option<bool?> Thing1
            = new global::System.CommandLine.Option<bool?>("--thing1", "-t")
            {
                HelpName = "Help name for thing1",
                Description = "Test Thing1",
            };
    }
}
