// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

namespace Ubiquity.NET.CommandLine
{
    /// <summary>Interface for binding operations for a command</summary>
    /// <typeparam name="T">Type of the final results of a bind operation</typeparam>
    /// <remarks>
    /// This provides a static interface for types that create <typeparamref name="T"/> from
    /// a <see cref="ParseResult"/> (bind).
    /// </remarks>
    public interface ICommandBinder<T>
        where T : ICommandBinder<T>
    {
        /// <summary>Binds the results of the parse to a new instance of <typeparamref name="T"/></summary>
        /// <param name="parseResult">Results of the parse to bind</param>
        /// <returns>Newly constructed instance of <typeparamref name="T"/> with properties bound from <paramref name="parseResult"/></returns>
        /// <remarks>
        /// <para>The implementation of this method allows pure source code AOT (Zero-Runtime-Reflection) binding.
        /// Normally this is generated by a source generator to leverage compile time reflection. But for simple
        /// applications hand generation is often used. (Until a generator is implemented that's the only
        /// option actually).</para>
        /// </remarks>
        /// <exception cref="System.InvalidOperationException">Thrown when required argument or option was not parsed or has no default value configured.</exception>
        public static abstract T Bind( ParseResult parseResult );
    }
}
