// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

namespace Ubiquity.NET.CommandLine
{
    /// <summary>Interface for a root command in command line parsing</summary>
    /// <remarks>
    /// <note type="tip">This only contains a static interface and thus requires the static abstract feature of the runtime.
    /// (.NET 7 or later) It is used to constrain methods to those that have static methods that are specifically
    /// designed for command line parsing.</note>
    /// </remarks>
    public interface IRootCommandBuilder
    {
        /// <summary>Builds a new <see cref="AppControlledDefaultsRootCommand"/> for parsing the command line</summary>
        /// <param name="settings">Settings to use for parsing</param>
        /// <returns>New <see cref="AppControlledDefaultsRootCommand"/> instance for the command</returns>
        /// <remarks>
        /// <para>
        /// The settings determine the default Options and Directives, etc... to add or remove from the command.
        /// <see cref="System.CommandLine.RootCommand"/> contains hard coded defaults without any construction
        /// configuration. <see cref="AppControlledDefaultsRootCommand"/> takes care of adding or removing things
        /// based on the <paramref name="settings"/> to make the defaults app controlled.
        /// </para>
        /// <para>Normally, this just creates an instance of <see cref="AppControlledDefaultsRootCommand"/> and initializes
        /// it with all of the <see cref="Symbol"/>s for a given command line</para>
        /// <para>
        /// The implementation of this method allows pure source code AOT (Zero-Runtime-Reflection) description.
        /// </para>
        /// </remarks>
        public static abstract AppControlledDefaultsRootCommand Build( CommandLineSettings settings );
    }

    /// <summary>Interface for a root command in command line parsing with settings</summary>
    /// <remarks>
    /// <note type="tip">This only contains a static interface and thus requires the static abstract feature of the runtime.
    /// (.NET 7 or later) It is used to constrain methods to those that have static methods that are specifically
    /// designed for command line parsing.</note>
    /// <para>The implementation of this method allows pure source code AOT (Zero-Runtime-Reflection) description.
    /// This is ideally provided by code generation tools from an attribute, though implementing such a thing has proven
    /// more difficult than is ideal. Though it is possible to specify this manually until such a thing exists or
    /// in more advanced scenarios.</para>
    /// </remarks>
    public interface IRootCommandBuilderWithSettings
    {
        /// <summary>Gets the <see cref="CommandLineSettings"/> to use for building this command</summary>
        public static abstract CommandLineSettings Settings { get; }

        /// <summary>Builds a new <see cref="AppControlledDefaultsRootCommand"/> for parsing the command line</summary>
        /// <returns>New <see cref="AppControlledDefaultsRootCommand"/> instance for the command</returns>
        /// <remarks>
        /// <para>
        /// The settings determine the default Options and Directives, etc... to add or remove from the command.
        /// <see cref="System.CommandLine.RootCommand"/> contains hard coded defaults without any construction
        /// configuration. <see cref="AppControlledDefaultsRootCommand"/> takes care of adding or removing things
        /// based on the <see cref="IRootCommandBuilderWithSettings.Settings"/> to make the defaults app controlled.
        /// </para>
        /// <para>Normally, this just creates an instance of <see cref="AppControlledDefaultsRootCommand"/> and initializes
        /// it with all of the <see cref="Symbol"/>s for a given command line</para>
        /// <para>The implementation of this method allows pure source code AOT (Zero-Runtime-Reflection) description.
        /// Normally, this is generated by a source generator to leverage compile time reflection. But for simple
        /// applications hand generation is often used.</para>
        /// </remarks>
        public static abstract AppControlledDefaultsRootCommand Build( );
    }
}
